Repository thoth-station/datasets, pull requests merged in 2020-06, with the labels that each got.

#2 Thoth Solver Dataset
  .gitattributes
  Pipfile
  Pipfile.lock
  README.md
  app.py
  notebooks/thoth-solver-dataset/ThothSolverDataset.ipynb
  notebooks/thoth-solver-dataset/thoth-solver-dataset-v1.0.zip
  template/__init__.py
  template/version.py
Labels: size/XXL

#3 Adjust links
  .github/CODEOWNERS
  README.md
Labels: approved, size/S

#4 Add instructions to use the notebook and dataset
  README.md
Labels: approved, size/S

#5 Correct readme command
  README.md
Labels: approved, size/S

#6 Add performance dataset
  README.md
  notebooks/thoth-performance-dataset/thoth-performance-dataset-v1.0.zip
Labels: approved, size/M

#8 Added version.py
  version.py
Labels: approved, size/XS

#9 Add notebook for Performance Dataset
  notebooks/thoth-performance-dataset/ThothPerformanceDataset.ipynb
  notebooks/thoth-solver-dataset/ThothSolverDataset.ipynb
Labels: approved, size/XXL

#10 Update readme
  README.md
Labels: size/XS

#13 Add missing info
  README.md
Labels: approved, size/XS
