Repository thoth-station/datasets, pull requests merged in 2022-01, with the labels that each got.

#57 Update pyproject.toml to use Python 3.8
  pyproject.toml
Labels: size/XS

#68 Script for generating public database dump
  generate_dump.sh
Labels: approved, size/S

#67 Instructions for accessing Thoth's public database on opf-datacatalog
  README.md
Labels: approved, size/S, lgtm
